### ISSUE TITLE
Social Network: API and NoSQL database

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/social-network#2]
# User Story:
Social media website needs to handle large amounts of unstructured data, so a NoSQL database will be created and Express APIs will handle CRUD operations to the database:

# User Requirements:
GIVEN a social network API
WHEN I enter the command to invoke the application
THEN my server is started and the Mongoose models are synced to the MongoDB database
WHEN I open API GET routes in Insomnia for users and thoughts
THEN the data for each of these routes is displayed in a formatted JSON
WHEN I test API POST, PUT, and DELETE routes in Insomnia
THEN I am able to successfully create, update, and delete users and thoughts in my database
WHEN I test API POST and DELETE routes in Insomnia
THEN I am able to successfully create and delete reactions to thoughts and add and remove friends to a user’s friend list

## Task
- [x] /api/users > GET ALL, GET by ID, POST, PUT, DELETE
- [x] /api/users/:userId/friends/:friendId > POST, DELETE
- [x] /api/thoughts > GET ALL, GET by ID, POST, PUT, DELETE
- [x] /api/thoughts/:thoughtId/reactions > POST, DELETE
- [x] Format date
- [x] create controllers

Bonus
- [x] Remove all thoughts after deleting user
